alias sudo='sudo '
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi='vim'
alias tf='terraform'
alias r='ranger'
alias pm='pulsemixer'
alias ...='../..'
alias ....='../../..'

alias ltev='~/src/local/start_session.sh'
alias lpev='~/src/local/start_session.sh cliqz-primary'

alias gss='git status -s'
alias gb='git branch'
alias gco='git checkout'
alias ga='git add'
alias gc='git commit'
alias glog='git log --oneline'
