alias sudo='sudo '
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi='vim'
alias tf='terraform'
alias r='ranger'
alias pm='pulsemixer'
alias ...='../..'
alias ....='../../..'

alias ltev='~/src/local/start_session.sh'
alias lpev='~/src/local/start_session.sh cliqz-primary'
alias aws-login='aws-vault login --duration 12h cliqz-primary'

alias gss='git status -s'
alias gb='git branch'
alias gco='git checkout'
alias ga='git add'
alias gc='git commit'
alias grb='git rebase'
alias glog='git log --oneline'

alias vpn-us='sudo openvpn ~/vpn/mullvad_us.conf'
alias vpn-hu='sudo openvpn ~/vpn/mullvad_hu.conf'
alias vpn-de='sudo openvpn ~/vpn/mullvad_de.conf'
alias vpn-gb='sudo openvpn ~/vpn/mullvad_gb.conf'

alias screen-hdmi='xrandr --output HDMI1 --auto --primary && xrandr --output eDP1 --off'
alias screen-dp='xrandr --output DP1-1 --auto --primary && xrandr --output eDP1 --off'
alias screen-int='xrandr --output eDP1 --auto --primary && xrandr --output HDMI1 --off && xrandr --output DP1-1 --off'
