alias sudo='sudo '
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi='vim'
alias tf='terraform'
alias r='ranger'
alias pm='pulsemixer'
alias ...='../..'
alias ....='../../..'

alias ltev='~/src/local/start_session.sh'
alias lpev='~/src/local/start_session.sh cliqz-primary'
alias aws-login='aws-vault login --duration 12h cliqz-primary'

alias gss='git status -s'
alias gs='git status -s'
alias gb='git branch'
alias gco='git checkout'
alias ga='git add'
alias gc='git commit'
alias grb='git rebase'
alias glog='git log --oneline'
alias gf='git fetch'
alias gp='git push'

alias screen-hdmi='xrandr --output HDMI1 --auto --primary && xrandr --output eDP1 --off'
alias screen-dp='xrandr --output DP1-1 --auto --primary && xrandr --output eDP1 --off'
alias screen-int='xrandr --output eDP1 --auto --primary && xrandr --output HDMI1 --off && xrandr --output DP1-1 --off'

alias csl='~/src/scripts/colorscheme.sh l'
alias csd='~/src/scripts/colorscheme.sh d'

# Start redshift (Munich)
alias rs='redshift -l 48.13743:11.57549 -m vidmode'
